import { Theme } from "../theme.slint";
export component HDivider inherits HorizontalLayout {
    in property <length> thickness: 1px;

    Rectangle {
        background: Theme.border-gray;
        horizontal-stretch: 1;
        height: thickness;
        border-radius: self.height / 2;
    }
}

export component VDivider inherits VerticalLayout {
    in property <length> thickness: 1px;

    Rectangle {
        background: Theme.border-gray;
        vertical-stretch: 1;
        width: thickness;
        border-radius: self.width / 2;
    }
}