import { Theme } from "../theme.slint";

export component NavButton inherits Rectangle {
    in property <string> title: "Title";

    in property <image> icon;
    in property <brush> icon_color: touch-click.has-hover ? Theme.text-inverse : Theme.text-primary;
    in property <length> icon_size_x: 24px;
    in property <length> icon_size_y: 24px;

    in property <brush> background_color: Theme.surface;
    in property <brush> text_color: touch-click.has-hover ? Theme.text-inverse : Theme.text-primary;
    in property <brush> hover_color: Theme.dark-mode ? Theme.button-tertiary : Theme.button-secondary;
    in property <brush> click_color: Theme.button;

    callback on_click();
    callback on_hover(bool);

    private property <bool> clicked: false;

    border-color: touch-click.has-hover && Theme.dark-mode ? Theme.border-selected :  Theme.border-gray;
    border-width: Theme.border-thin;

    height: 28px;

    background: clicked ? click_color
        : touch-click.has-hover ? hover_color
        : background_color;

    animate width, background {
        duration: 300ms;
        easing: ease-out;
    }

    HorizontalLayout {
        alignment: center;
        Rectangle {
            Image {
                source: icon;
                colorize: icon_color;
                width: icon_size_x;
                height: icon_size_y;

                animate colorize {
                    duration: 300ms;
                    easing: ease-out;
                }
            }
        }
    }



    touch-click := TouchArea {
        clicked => {
            root.clicked = true;
            root.on_click();
            reset-timer.running = true;
        }
        changed has-hover => {
            root.on_hover(self.has-hover);
        }
    }

    reset-timer := Timer {
        interval: 90ms;
        running: false;
        triggered => {
            root.clicked = false;
            self.running = false;
        }
    }
}