
import { ButtonIcon } from "icon_button.slint";
import { Theme, Icon } from "../theme.slint";
import { NavButton } from "nav_button.slint";
import { Container } from "container.slint";
import { NavbarCard } from "cards.slint";
import { ScrollView } from "std-widgets.slint";
import { SidebarEntryData } from "data.slint";

export component Sidebar inherits Rectangle {
    in-out property <bool> toggled : true;
    in-out property <[SidebarEntryData]> entries;

    HorizontalLayout {
        padding-left: Theme.spacing-sm;
        padding-bottom: Theme.spacing-xs;
        alignment: stretch;

        VerticalLayout {
            NavButton {
                height: 36px;
                border-radius: self.height / 2;
                icon: toggled ? Icon.double_arrow_l : Icon.double_arrow_r;
                icon_size_x: 24px;
                icon_size_y: 24px;

                border-bottom-left-radius: 0;
                border-bottom-right-radius: 0;

                title: "Games";
                text_color: Theme.text-inverse;

                on_hover(is-hovered) => {
                }
                on_click => {
                    toggled = !toggled;
                }
            }

            Container {
                background: Theme.surface;
                clip: true;
                width: toggled ? 264px : 40px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
                border-bottom-left-radius: Theme.radius-md;
                border-bottom-right-radius: Theme.radius-md;

                border-color: Theme.border-gray;
                border-width: Theme.border-thin;

                animate width {
                    duration: 50ms;
                    easing: ease-out;
                }
                scroll := ScrollView {
                    width: parent.width;
                    vertical-scrollbar-policy: as-needed;


                    property <bool> at-top: scroll.viewport-y >= 0px;
                    property <bool> at-bottom: scroll.viewport-height <= scroll.visible-height ||
                        scroll.viewport-y <= -(scroll.viewport-height - scroll.visible-height);

                    animate width {
                        duration: 200ms;
                        easing: ease-out;
                    }
                    VerticalLayout {
                        padding-left: Theme.spacing-xxs;
                        padding-right: Theme.spacing-xxs;
                        padding-top: Theme.spacing-xxs;
                        spacing: Theme.spacing-xs;
                        alignment: start;
                        vertical-stretch: 0;
                        // TODO: hook this up
                        for entry in root.entries : NavbarCard {
                            NavbarCard {
                                data: entry;
                            }
                        }
                        NavbarCard {
                            small: toggled;
                            selected: true;
                        }
                        NavbarCard {
                            small: toggled;
                        }
                        NavbarCard {
                            small: toggled;
                        }
                        NavbarCard {
                            small: toggled;
                        }
                        NavbarCard {
                            small: toggled;
                        }
                        NavbarCard {
                            small: toggled;
                        }
                        NavbarCard {
                            small: toggled;
                        }
                    }
                }
                // Top fade, show when scrolled down
                Rectangle {
                    y: 0;
                    width: parent.width;
                    opacity: scroll.at-bottom ? 0.0 : 1.0;
                    background: Theme.gradient-vertical-fade-top;
                    animate opacity { duration: 200ms; }
                }

                // Bottom fade, show when there's more content below
                Rectangle {
                    y: parent.height - self.height;
                    width: parent.width;
                    opacity: scroll.at-top ? 0.0 : 1.0;
                    background: Theme.gradient-vertical-fade-bottom;
                    animate opacity { duration: 200ms; }
                }
            }
        }
    }
}