import { Theme, Icon } from "../theme.slint";
import { Button, Switch } from "std-widgets.slint";
import { SwitchButton } from "switch_button.slint";
import { TooltipArea } from "tooltip.slint";
import { ButtonIcon } from "icon_button.slint";

export component TitleBar inherits Rectangle {
    height: 45px;
    y: 0;

    in property <string> app_version: "v0.7.4";
    in property <string> title: "Steam Workshop Utility";

    callback drag(length, length);
    callback minimize();
    callback maximize();
    callback close();

    // Drag area (behind everything)
    TouchArea {
        width: parent.width;
        height: parent.height;
        moved => {
            if (self.pressed) {
                root.drag(self.mouse-x - self.pressed-x, self.mouse-y - self.pressed-y);
            }
        }
    }

    HorizontalLayout {
        padding-left: Theme.spacing-sm;
        padding-right: Theme.spacing-sm;
        padding-top: Theme.spacing-xs;
        padding-bottom: Theme.spacing-xs;
        alignment: stretch;

        // Title
        HorizontalLayout {
            spacing: Theme.spacing-xxs;
            horizontal-stretch: 0;
            alignment: start;
            Rectangle {
                width: 24px;
                vertical-stretch: 1;
                Image {
                    source: Icon.steam;
                    colorize: Theme.button-secondary;
                    width: 24px;
                    height: 24px;
                    y: (parent.height - self.height) / 2;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }
            Text {
                vertical-alignment: center;
                text: "SWU";
                color: Theme.gradient-vertical;
                font-size: Theme.font-heading;
                font-weight: Theme.weight-bold;
                font-family: Theme.font-family;
            }
            Text {
                y: 3px;
                vertical-alignment: center;
                text: root.app-version;
                color: Theme.text-secondary;
                font-size: Theme.font-tiny;
                font-family: Theme.font-family;
            }
        }

        HorizontalLayout {
            alignment: center;
            horizontal-stretch: 1;
            Text {
                vertical-alignment: center;
                text: title;
                color: Theme.text-secondary;
                font-size: Theme.font-small;
                font-weight: Theme.weight-thin;
                font-family: Theme.font-family;
            }
        }

        // Window controls
        HorizontalLayout {
            spacing: 0;
            horizontal-stretch: 0;
            alignment: end;

            HorizontalLayout {
                padding-right: Theme.spacing-sm;
                TouchArea {
                    SwitchButton {
                        toggled: Theme.dark-mode;
                        toggled-changed(val) => {
                            Theme.dark-mode = val;
                        }

                    }
                    changed has-hover => {
                        tooltip.show-tooltip(
                            self.has-hover,
                            self.absolute-position.x + self.mouse-x,
                            self.absolute-position.y + self.mouse-y,
                            "Toggle Light/Dark Mode"
                        );
                    }
                }
            }


            // Minimize
            ButtonIcon {
                border-top-left-radius: self.height / 2;
                border-bottom-left-radius: self.height / 2;
                icon: Icon.minimize;
                on_click => {
                    root.minimize();
                }
            }

            // Maximize
            ButtonIcon {
                icon: Icon.maximize;
                on_click => {
                    root.maximize();
                }
            }

            // Close
            ButtonIcon {
                border-top-right-radius: self.height / 2;
                border-bottom-right-radius: self.height / 2;
                icon: Icon.close;
                on_click => {
                    root.close();
                }
            }
        }
    }

    tooltip := TooltipArea {
        y: 50px;
    }
}