import { Theme, Icon } from "../theme.slint";
import { SwitchButton } from "switch_button.slint";
import { TooltipArea } from "tooltip.slint";
import { ButtonIcon } from "icon_button.slint";
import { Container } from "container.slint";
import { SearchBar } from "search_bar.slint";
import { Checkbox } from "checkbox.slint";

export component TopBar inherits HorizontalLayout {
    padding-left: Theme.spacing-sm;
    padding-right: Theme.spacing-sm;
    alignment: stretch;
    Container {
        background: Theme.surface;
        clip: true;
        height: 48px;
        VerticalLayout {
            padding-left: Theme.spacing-xs;
            padding-right: Theme.spacing-xs;
            alignment: center;

            HorizontalLayout {
                alignment: stretch;
                spacing: Theme.spacing-xs;
                VerticalLayout {
                    alignment: center;
                    Checkbox {
                        label: "15 Item(s)";
                        // Todo: Make this select all
                        toggled(val) => {
                        }
                    }
                }
                SearchBar {
                    horizontal-stretch: 1;
                }

                VerticalLayout {
                alignment: center;
                    ButtonIcon {
                        width: 36px;
                        height: 36px;
                        border-radius: self.height / 2;
                    }
                }

            }
        }
    }
}